version: '3.3'

services:
   db:
     image: docker.pkg.github.com/zhufacai/qiongbi/web:latest
     volumes:
       - ./data/:/qiongbi/data
     restart: always
     ports:
       - "0.0.0.0:8001:8080"
     environment:
       - AppID=
       - PubKey=
       - PriKey=
       - Domain=
