version: '3.3'

services:
   db:
     image: docker.pkg.github.com/naiba/qiongbi/web:latest
     volumes:
       - ./data/:/qiongbi/data
     restart: always
     ports:
       - "172.17.0.1:8001:8080"
     environment:
       - AppID=qiongbi
       - PubKey=xxxxxx
       - PriKey=xxxxxx
       - Domain=example.com